# Generated by Django 5.1.4 on 2025-07-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='membership_type',
            field=models.CharField(choices=[('student', '学生'), ('admin', '管理者')], default='student', max_length=10),
        ),
    ]
